//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Notifiers = new HashSet<Notifier>();
        }
    
        public int Id { get; set; }
        public int User_id { get; set; }
        public int Customer_id { get; set; }
        public int Treatment_id { get; set; }
        public System.DateTime Time_stamp { get; set; }
        public System.DateTime Time_end { get; set; }
        public Nullable<int> Status_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Status Status { get; set; }
        public virtual Treatment Treatment { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Notifier> Notifiers { get; set; }
    }
}
