//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Bookings = new HashSet<Booking>();
            this.Contacts = new HashSet<Contact>();
        }
    
        public int Id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
