//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roster
    {
        public int Id { get; set; }
        public int User_id { get; set; }
        public int Year { get; set; }
        public int Week { get; set; }
        public Nullable<System.DateTime> Day1_start { get; set; }
        public Nullable<System.DateTime> Day1_end { get; set; }
        public Nullable<System.DateTime> Day2_start { get; set; }
        public Nullable<System.DateTime> Day2_end { get; set; }
        public Nullable<System.DateTime> Day3_start { get; set; }
        public Nullable<System.DateTime> Day3_end { get; set; }
        public Nullable<System.DateTime> Day4_start { get; set; }
        public Nullable<System.DateTime> Day4_end { get; set; }
        public Nullable<System.DateTime> Day5_start { get; set; }
        public Nullable<System.DateTime> Day5_end { get; set; }
        public Nullable<System.DateTime> Day6_start { get; set; }
        public Nullable<System.DateTime> Day6_end { get; set; }
        public Nullable<System.DateTime> Day7_start { get; set; }
        public Nullable<System.DateTime> Day7_end { get; set; }
    
        public virtual User User { get; set; }
    }
}
