//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalonEntities : DbContext
    {
        public SalonEntities()
            : base("name=SalonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Booking> Bookings { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Notifier> Notifiers { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Roster> Rosters { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Treatment> Treatments { get; set; }
        public DbSet<Treatment_type> Treatment_type { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
