//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public Treatment()
        {
            this.Bookings = new HashSet<Booking>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Treatment_name { get; set; }
        public decimal Treatment_cost { get; set; }
        public int Treatment_type_id { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Treatment_type Treatment_type { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
