//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment_type
    {
        public Treatment_type()
        {
            this.Treatments = new HashSet<Treatment>();
        }
    
        public int Id { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Treatment> Treatments { get; set; }
    }
}
