//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Bookings = new HashSet<Booking>();
            this.Notifiers = new HashSet<Notifier>();
            this.Rosters = new HashSet<Roster>();
        }
    
        public int Id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public int Role_id { get; set; }
        public int Treatment_id { get; set; }
        public int Contact_id { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Notifier> Notifiers { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Roster> Rosters { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
